version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "9090:80"
    depends_on:
      - db

volumes:
  db_data:
